language: node_js
node_js:
  - '7'
  - '6'
  - '5'
  - '4'
  - 'iojs'
  - '0.12'
  - '0.10'
before_script:
  - 'if [ "${TRAVIS_NODE_VERSION}" = "iojs" ] || [ "${TRAVIS_NODE_VERSION}" = "0.12" ] || [ "${TRAVIS_NODE_VERSION}" = "0.10" ]; then npm install eslint@2 babel-eslint@6; fi'
after_success:
  - npm run coveralls
matrix:
  fast_finish: true
  allow_failures:
